# Generated by Django 5.1.4 on 2024-12-27 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='lvl',
            new_name='level',
        ),
    ]
